const data = {
    products: [
        {
            name: 'Free Shirt',
            category: 'Shirts',
            image: '/images/pants3.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
        }, {
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/pants2.jpg',
            price: 40,
            brand: 'Adidas',
            rating: 4.2,
            numReviews: 13,
            countInStock: 22,
            description: 'Another popular shirt',
        }, {
            name: 'Best Basic Shirt',
            category: 'Shirts',
            image: '/images/pants1.jpg',
            price: 10,
            brand: 'Basic',
            rating: 2.5,
            numReviews: 100,
            countInStock: 80,
            description: 'A basic shirt',
        }, {
            name: 'Free Pant',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular pant',
        }, {
            name: 'Free Pant',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 89,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 45,
            countInStock: 10,
            description: 'Another pant',
        }, {
            name: 'Basis Pant',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 10,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 80,
            countInStock: 60,
            description: 'A basic pant',
        },
    ],
};

export default data;